Fix in operator & and/or precedence
osohq/oso pull request #1042
Opened 2021-08-02 14:35 UTC by gw000

Sorry to drop these so close to release time but ...

- Fix the `in` operator to handle rest variables
- Make `or` have lower precedence than `and`, to match every other language

PR checklist:

- [ ] Added changelog entry.

2021-08-02 14:53 UTC, saolsen commented
Making `and` have the lowest precedence was an intentional move so that rule bodies would always be an `and` and to match the way it works in prolog. I'm not really sure if that matters though or if we depend on it anywhere. We did that back when we had prolog syntax and didn't call them `and` and `or`. This has tricked users before so I'm into changing it, just a little worried that we depend on it in some subtle ways. I think it's probably fine if the tests pass. This is a big one to flag in the changelog too.

2021-08-02 15:15 UTC, gw000 commented
Interesting. I'm happy to take that change out if we want to stick with that design choice, but it does seem pretty confusing. It may be internally convenient for rule bodies to always be an `and`, but that shouldn't be allowed to dictate the user experience IMO. It also breaks the analogy `&& : || :: * : +`.

2021-08-02 15:19 UTC, gw000 commented on polar-core/tests/integration_tests.rs
> +    assert!(matches!(a,
So I updated this test to expect a new expression, and the expression seems to be correct, but actually I'm a little confused about what we're trying to test here. The constraint described by the expression is basically "a is a list containing a list".

2021-08-02 15:41 UTC, saolsen commented
> Interesting. I'm happy to take that change out if we want to stick with that design choice, but it does seem pretty confusing. It may be internally convenient for rule bodies to always be an `and`, but that shouldn't be allowed to dictate the user experience IMO. It also breaks the analogy `&& : || :: * : +`.

Yeah I agree. I also don't think the rule body thing is even a problem after thinking about it, the whole body is wrapped in an `and` anyway so it'd be an `and` with an `or` in it and work just fine.

2021-08-02 15:46 UTC, saolsen requested changes
There's a table in `formatting.rs` that needs to be updated that records all the precedences and uses them to output terms in polar syntax.

2021-08-02 19:45 UTC, dhatch commented
What's this part of the change?

> Fix the in operator to handle rest variables

Does it need to be in the changelog?

2021-08-02 19:50 UTC, dhatch commented
> What's this part of the change?
> 
> > Fix the in operator to handle rest variables
> 
> Does it need to be in the changelog?

Nvm.

2021-08-02 19:50 UTC, dhatch commented
Can you add a new test for the `in` behavior though? I don't see it covered in any here.

2021-08-02 19:56 UTC, dhatch commented on polar-core/src/polar.lalrpop
> +Exp1<T>: ValueOrLogical = {
Can we swap this & `OrExp` w/ `Exp1` & `AndExp` so this file remains in precedence order after the change?

2021-08-03 14:34 UTC, gw000 commented
precedence change isn't going out this release; other fix is in https://github.com/osohq/oso/pull/1047

2021-08-03 14:34 UTC, closed without merging