Add target to run docs without api docs.
osohq/oso pull request #1087
Opened 2021-08-18 16:36 UTC by dhatch

2021-08-20 19:41 UTC, gkaemmer requested changes
Let's get rid of the package-lock, unless you added it for a reason. Other than that looks good.

Maybe also add a `dev` task? 😃
```
dev: install
  HUGO_PURGECSS=false hugo server
```

2021-08-21 03:33 UTC, gj approved these changes
Don't particularly care whether or not these lockfiles remain version-controlled, but we should probably standardize on Yarn or NPM project-wide. I think we use Yarn in most places.

2021-08-21 03:33 UTC, gj commented on docs/Makefile
>  	hugo server
nit

```suggestion
run: api_docs
	$(MAKE) run_without_api_docs
```

2021-08-24 15:23 UTC, dhatch commented
> should probably standardize on Yarn or NPM project-wide. I think we use Yarn in most places.

@gj Is using Yarn vs. NPM the reason the lock file version changed?

2021-08-24 15:31 UTC, gkaemmer approved these changes

2021-08-24 15:41 UTC, merged

2021-08-24 17:53 UTC, gj commented
> > should probably standardize on Yarn or NPM project-wide. I think we use Yarn in most places.
> 
> @gj Is using Yarn vs. NPM the reason the lock file version changed?

nope; using Yarn would've generated a (new) `yarn.lock` file in addition to the existing `package-lock.json` file generated by NPM