pub docs.
osohq/oso pull request #1204
Opened 2021-09-15 21:00 UTC by dhatch

2021-09-15 21:01 UTC, samscott89 requested changes
doesnt look right. before some mashes approve

2021-09-15 21:02 UTC, samscott89 approved these changes
I take it back `make ci-prod-docs` is good :)

2021-09-15 21:04 UTC, samscott89 commented on .github/workflows/publish-docs.yml
> -        run: aws cloudfront create-invalidation --distribution-id E1MY35FKBOYAV1 --paths "/*"
You'll want to keep this invalidation so that the root still invalidates

2021-09-21 20:55 UTC, samscott89 requested changes
Shall we delete all the docs-preview publishing steps? Those aren't really getting us anything since all branches are deployed to docs preview anyway.

2021-09-22 21:27 UTC, dhatch commented
> Shall we delete all the docs-preview publishing steps? Those aren't really getting us anything since all branches are deployed to docs preview anyway.

Thought about it but I wanted to be able to test this job.

2021-09-22 21:38 UTC, dhatch commented
Tested here: https://github.com/osohq/oso/runs/3680497127?check_suite_focus=true

2021-09-24 14:34 UTC, samscott89 approved these changes

2021-09-24 14:34 UTC, samscott89 commented on .github/workflows/publish-docs.yml
> +        run: s3deploy -bucket ${{ github.event.inputs.url }} -distribution-id E1MY35FKBOYAV1 -path v/main -source public -region us-east-1
```suggestion
        run: s3deploy -bucket ${{ github.event.inputs.url }}  -path v/main -source public -region us-east-1
```

2021-09-24 14:35 UTC, samscott89 commented on .github/workflows/publish-docs.yml
> +        run: s3deploy -bucket ${{ github.event.inputs.url }} -distribution-id E1MY35FKBOYAV1 -path v/main -source public -region us-east-1
This would be better actually, a little less redundant since the next steps invalidate it again.

2021-09-27 17:00 UTC, merged