add py.typed to sqlalchemy-oso
osohq/oso pull request #1220
Opened 2021-09-22 19:59 UTC by leina05

2021-09-22 20:42 UTC, dhatch commented
Did you test this by confirming users can see type annotations?

2021-09-27 16:52 UTC, dhatch approved these changes

2021-09-27 17:04 UTC, gj requested changes
@dhatch:

> Doesn’t need another review but it would be great to test by building the wheel & confirming it has annotations
>
> Getting the settings right in setup.py can impact whether py.typed actually gets built in the wheel

@leina05 you can dismiss this review once you've confirmed the above

2021-09-27 22:23 UTC, leina05 commented
Confirmed

2021-09-27 22:39 UTC, merged