add polar file load to repl example
osohq/oso pull request #1432
Opened 2021-12-08 15:54 UTC by saolsen

2021-12-13 16:33 UTC, dhatch requested changes

2021-12-13 16:33 UTC, dhatch commented on docs/content/node/reference/tooling/repl/data/data.md
> +    oso.loadFiles(["alice.polar"])
Needs await, right?

2021-12-21 16:42 UTC, saolsen commented on docs/content/node/reference/tooling/repl/data/data.md
> +    oso.loadFiles(["alice.polar"])
uhhh yeah I think so

2021-12-21 16:42 UTC, saolsen commented on docs/content/node/reference/tooling/repl/data/data.md
> +    oso.loadFiles(["alice.polar"])
```suggestion
    await oso.loadFiles(["alice.polar"])
```

2021-12-21 16:42 UTC, dhatch commented on docs/content/node/reference/tooling/repl/data/data.md
> +    oso.loadFiles(["alice.polar"])
lgtm after that

2021-12-21 16:42 UTC, dhatch approved these changes

2021-12-21 16:58 UTC, merged