refactor: Clarify error when right_path exists
osohq/oso pull request #1555
Opened 2022-04-09 02:17 UTC by kkirsche

Fixes #1552

This commit catches the assertion error when verifying the `right_path`
does not exist when a path has been identified on the left side of the
policy. This refactor was made to better clarify the cause of the error
for developers who may not be familiar with the technical limitations of
the current SQLAlchemy integration.

In my case, I had assumed that the use of foreign keys and paths on both
sides would be more performant, and thus the best choice for a policy,
when writing the authorization rules. The resulting error didn't include
any context about what was wrong with the policy I had written. This
commit aims to address this by providing a best effort guess to provide
a starting point for developers to debug the policy issue themselves.

PR checklist:

- [ ] Added changelog entry.

2022-04-09 02:18 UTC, kkirsche commented
I have read the CLA Document and I hereby sign the CLA

2022-04-11 17:51 UTC, gw000 commented
Hi @kkirsche , how about
```
if not right_path:
    raise PolarException(...)
```
instead of catching the assertion error?

2022-04-11 18:13 UTC, gw000 requested changes
Fix the error type, replace `try/assert/except/raise` with `if/raise` and this is good to go 😃

2022-04-11 18:13 UTC, gw000 commented on languages/python/sqlalchemy-oso/sqlalchemy_oso/partial.py
> +            raise PolarException(
I think you mean `PolarRuntimeError`?

2022-04-11 20:03 UTC, kkirsche commented
> Hi @kkirsche , how about
> 
> ```
> if not right_path:
>     raise PolarException(...)
> ```
> 
> instead of catching the assertion error?

Great point, I accidentally missed that.

That and the specific error being raised should be fixed in eb7c26e. Sorry again about the mix up there, but thank you for catching it 👍

2022-04-11 21:09 UTC, gw000 requested changes
One more change sorry!

2022-04-11 21:09 UTC, gw000 commented on languages/python/sqlalchemy-oso/sqlalchemy_oso/partial.py
> +            ) from e
`e` is undefined

2022-04-12 13:45 UTC, gw000 commented
There's still a test that's failing. Are you able to fix it?

2022-05-05 13:07 UTC, kkirsche commented
I'll take a look once the tests run after the latest merge of `main` into this branch, @gw000, and I will see if this is something I can clean up or if it's something that the team may be able to assist me in fixing. I will need to do it iteratively due to the errors with the toolchain I was experiencing. Once I see the error in the Github Action, I'll have a better understanding of what will be involved in this change.

Sorry for the delay in responding. A few time-sensitive items came up that I had to work through. I appreciate your patience.

2022-05-05 13:19 UTC, kkirsche commented
I'll see if I can fix it, but I can't run tests at all locally so this will come down to how quickly does trying to work with the toolchain become frustrating and I give up on it.

If someone with a deeper understanding of your toolchain is able to assist, that would be hugely helpful for this (and I can grant access to the branch / repo for that help) or I'll probably end up closing this PR if I can't figure it out as the toolchain is sufficiently complex that I can't really do local development for small contributions like this

2022-05-05 13:25 UTC, kkirsche commented
```
In [1]: assert not ()

In [2]: if not ():
   ...:     print("HERE")
   ...:
HERE
```

Ah, the criteria for assert and if are different, so the right path of `()` in the if statement is triggering the new error while the old assert ignored this

2022-05-05 13:36 UTC, kkirsche commented
The force pushes above were due to me realizing a better approach. Originally, I had updated this to use:

```python
if len(right_path) > 0:
```

because `dot_path` returns a `Tuple` type, this would work. Once I stepped back for a second though, I realized all I had done was swap the conditional's negation.

The force push updated this to:

```python
if right_path
```

The final one fixed the commit message so that it properly reflected the change that was included. Theoretically, if I understood this properly, the tests should pass

2022-05-13 17:52 UTC, kkirsche commented
Branch updated based on main — PR is pending re-review.

2022-06-09 03:04 UTC, kkirsche commented
Branch updated based on main — PR is pending re-review by a member of the Oso team.

2022-06-13 15:39 UTC, kkirsche commented
Course, f I hit this, other people may also run into this, so the more we can do to help them, the better 👍

2022-06-13 20:01 UTC, merged