Copy old docs spelling dictionary to new docs
osohq/oso pull request #819
Opened 2021-04-03 00:33 UTC by litonico

I noticed that I used a word in https://github.com/osohq/oso/pull/815 ("ad-hoc") that was in the old docs spelling dictionary, but not the new docs dictionary, so I merged the old into the new. This also adds adds a flag to `sort` to deduplicate our spelling dictionary.

2021-04-05 16:05 UTC, dhatch approved these changes
lgtm

2021-04-05 16:25 UTC, dhatch requested changes
Just discussed with @gj. We may want to just add the old words as needed, some of these are not words that should be in our dictionary (`rc`, `vec`, `usize`, `de`) that may have been needed due to errors / idiosyncrasies with the old docs spell checker.

The change to deduplicate the dictionary is a good idea, we should definitely keep that.

2021-04-07 22:05 UTC, litonico commented
Updated! This is now just the deduplication flag — I'll add whichever words I need on a per-PR basis.

2021-04-08 13:26 UTC, dhatch approved these changes
lgtm - thanks Lito!

2021-04-08 13:26 UTC, merged