fix removed rust quickstart
osohq/oso pull request #850
Opened 2021-04-14 21:27 UTC by dhatch

2021-04-14 21:31 UTC, gj requested changes
Still missing .gitmodules entry?

2021-04-14 22:21 UTC, gj approved these changes

2021-04-14 22:22 UTC, gj commented
Submodule accidentally removed in #827

2021-04-14 22:33 UTC, merged

2021-04-15 13:53 UTC, dhatch commented
Thanks for fixing