Add documentation to partial.py.
osohq/oso pull request #914
Opened 2021-05-20 15:44 UTC by dhatch

2021-05-24 21:10 UTC, leina05 requested changes
These are really helpful docs, thanks Dave. Left a few comments, I know the hairier methods are harder to explain in docstrings.

2021-05-24 21:10 UTC, leina05 commented on languages/python/sqlalchemy-oso/sqlalchemy_oso/partial.py
> +    """Translate an Isa operation. (matches keyword)
```suggestion
    """Translate an Isa operation. (``matches`` keyword)
```

Unsure if it's supposed to be 1 or 2 backticks, but looks like you're using 2 everywhere else.

2021-05-24 21:10 UTC, leina05 commented on languages/python/sqlalchemy-oso/sqlalchemy_oso/partial.py
> +    Also handle _this = ? where ? is an instance of the same type as _this.
```suggestion
    Also handle unification of _this with an instance of the same type as _this. E.g., _this = ? where ? is an instance of the same type as _this.
```

2021-05-24 21:10 UTC, leina05 commented on languages/python/sqlalchemy-oso/sqlalchemy_oso/partial.py
> +    _this.path.(path1)+.tail OP val => Model.path.(path1)+.has(Target.tail OP val)
I don't really understand this notation

2021-05-24 21:10 UTC, leina05 commented on languages/python/sqlalchemy-oso/sqlalchemy_oso/partial.py
> +    # this
Might need to clean this up.

2021-05-24 21:10 UTC, leina05 commented on languages/python/sqlalchemy-oso/sqlalchemy_oso/partial.py
> +    """Translate the in operator.
What is "relationship" referring to here?

2021-05-24 21:10 UTC, leina05 commented on languages/python/sqlalchemy-oso/sqlalchemy_oso/partial.py
> +    """Translate an operation over a path.
Could you describe each of the params?

2021-07-29 16:19 UTC, dhatch commented
@leina05 I don't really have time to update this but I'd like to merge as is if you're okay with it. I think some documentation is helpful even if it's not ideal.

2021-07-29 22:24 UTC, leina05 approved these changes

2021-08-05 18:41 UTC, merged