Make Query an enumerable to avoid running queries on fibers.
osohq/oso pull request #965
Opened 2021-06-12 23:45 UTC by samscott89

Minimal test case:

```ruby
require 'oso'

oso = Oso.new

class Foo
    def self.tv(name)
        Thread.current[name]
    end
end

oso.register_class(Foo)

Thread.current[:foo] = "bar"
oso.load_str('?= Foo.tv("foo") = "bar";')
```

Before this would fail, because the query runs on a fiber and thread variables are not accessible (without using `Thread.current.thread_variable_set` instead).

PR checklist:

- [ ] Added changelog entry.

2021-06-12 23:46 UTC, samscott89 commented on languages/ruby/spec/oso/polar/polar_spec.rb
> +        # you need to use load string here or it might not
I don't fully get this, but if you use `expect(qvar(...` like the other test cases the bad behaviour doesn't get triggered.

2021-06-13 17:00 UTC, samscott89 commented on languages/ruby/lib/oso/polar/query.rb
> +            yield event.data['bindings'].transform_values { |v| host.to_ruby(v) }
I think?
```suggestion
            return event.data['bindings'].transform_values { |v| host.to_ruby(v) }
```

2021-06-13 17:03 UTC, samscott89 commented on languages/ruby/spec/oso/polar/polar_spec.rb
> +        # you need to use load string here or it might not
I'm guessing if you return the enumerator in the test, then Ruby figures out it doesn't need to create a new fiber to evaluate the query, so it all happens on the right thread.

2021-06-15 02:42 UTC, gj approved these changes
kinda want to wrap `.first.nil?` in a method, but to be fair 98% of the calls are in the parity tests, which weren't exactly a paragon of readability to begin with

2021-06-15 02:43 UTC, gj requested changes
changelog first

good work tho 🦾

2021-06-15 16:32 UTC, gj approved these changes

2021-06-15 16:32 UTC, merged